default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 192.168.82.2

development:
  <<: *default
  database: rails5_dev

test:
  <<: *default
  database: rails5_test

production:
  <<: *default
  database: rails5_prod
