default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: vcms
  password: Vms.1946!
  host: mysql.varland.com

development:
  <<: *default
  database: rails5_dev

test:
  <<: *default
  database: rails5_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: mysql.varland.com
  database: rails5_prod
